Traceback (most recent call last):
  File "examples/cifar10.py", line 28, in <module>
    import torch
  File "/home/sandhya/.local/lib/python3.8/site-packages/torch/__init__.py", line 236, in <module>
    _load_global_deps()
  File "/home/sandhya/.local/lib/python3.8/site-packages/torch/__init__.py", line 195, in _load_global_deps
    raise err
  File "/home/sandhya/.local/lib/python3.8/site-packages/torch/__init__.py", line 176, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/sandhya/.local/lib/python3.8/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1346, in _path_importer_cache
KeyError: '/home/sandhya/.local/lib/python3.8/site-packages/torch/onnx/_internal/diagnostics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1324, in _path_hooks
  File "<frozen zipimport>", line 88, in __init__
zipimport.ZipImportError: not a Zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/cifar10.py", line 33, in <module>
    import torchvision.transforms as transforms
  File "/home/sandhya/.local/lib/python3.8/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/home/sandhya/.local/lib/python3.8/site-packages/torchvision/models/__init__.py", line 2, in <module>
    from .convnext import *
  File "/home/sandhya/.local/lib/python3.8/site-packages/torchvision/models/convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "/home/sandhya/.local/lib/python3.8/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from ._register_onnx_ops import _register_custom_op
  File "/home/sandhya/.local/lib/python3.8/site-packages/torchvision/ops/_register_onnx_ops.py", line 5, in <module>
    from torch.onnx import symbolic_opset11 as opset11
  File "/home/sandhya/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 10, in <module>
    from . import (  # usort:skip. Keep the order instead of sorting lexicographically
  File "/home/sandhya/.local/lib/python3.8/site-packages/torch/onnx/errors.py", line 9, in <module>
    from torch.onnx._internal import diagnostics
  File "/home/sandhya/.local/lib/python3.8/site-packages/torch/onnx/_internal/diagnostics/__init__.py", line 1, in <module>
    from ._diagnostic import (
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1376, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1348, in _path_importer_cache
  File "<frozen importlib._bootstrap_external>", line 1324, in _path_hooks
KeyboardInterrupt
Traceback (most recent call last):
  File "examples/cnn3.py", line 12, in <module>
    from opacus import PrivacyEngine
ModuleNotFoundError: No module named 'opacus'
